name: CI Pipeline to run lint | unit tests & sonarcloud check

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Find modified projects
        run: |
          echo "command: git branch"
          git branch
          echo "command: git branch -r"
          git branch -r
          touch modified-projects.txt
          git diff --name-only ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF} | grep -v -E '^(.github)/' | awk -F '/' '{print $1}' | uniq > modified-projects.txt
          echo "command: ls -alh"
          ls -alh
          echo "command: pwd"
          pwd
          echo "command: cat modified-projects.txt"
          cat modified-projects.txt

      - name: Print modified projects
        run : |
          echo "command: ls -alh"
          ls -alh
          echo "command: pwd"
          pwd
          echo "command: cat modified-projects.txt"
          cat modified-projects.txt
          # Check if the file is empty
          if [ -s modified-projects.txt ]; then
            echo "No modified project found!"
            exit 0
          else
            echo "Below are modified projects:"
            echo "-----------------------------"
            cat modified-projects.txt
          fi
